import Foundation
import Testing
@testable import Familiar

@Suite("Canonical byte store parent-link isolation", .serialized)
struct FamiliarFilePathBoundaryTests {
    @Test("A real system ancestor alias remains usable; a final file link is refused")
    func realAncestorAlias() throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent("FC-ancestor-" + UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: root) }
        let real = root.appendingPathComponent("Real")
        try FileManager.default.createDirectory(at: real, withIntermediateDirectories: true)
        let alias = root.appendingPathComponent("Alias")
        try FileManager.default.createSymbolicLink(at: alias, withDestinationURL: real)
        let store = FamiliarFileStore(rootURL: alias.appendingPathComponent("Store"))
        let output = try store.write(Data("real bytes".utf8), projectID: UUID(), fileID: UUID(), filename: "valid.txt")
        #expect(try store.read(relativePath: output.path) == Data("real bytes".utf8))
        let source = store.rootURL.appendingPathComponent(output.path)
        let link = source.deletingLastPathComponent().appendingPathComponent("alias.txt")
        try FileManager.default.createSymbolicLink(at: link, withDestinationURL: source)
        #expect(store.url(relativePath: output.path.replacingOccurrences(of: "valid.txt", with: "alias.txt")) == nil)
    }

    @Test("A generated byte-store Project parent cannot redirect to a foreign Project")
    func generatedParentLink() throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent("FC-file-path-" + UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: root) }
        let a = UUID(), b = UUID(), fileID = UUID()
        let store = FamiliarFileStore(rootURL: root)
        let saved = try store.write(Data("B private bytes".utf8), projectID: b, fileID: fileID, filename: "secret.txt")
        let link = root.appendingPathComponent("Projects/" + a.uuidString)
        try FileManager.default.createSymbolicLink(at: link, withDestinationURL: root.appendingPathComponent("Projects/" + b.uuidString))
        let disguised = saved.path.replacingOccurrences(of: b.uuidString, with: a.uuidString)
        #expect(throws: (any Error).self) { _ = try store.read(relativePath: disguised) }
        #expect(store.url(relativePath: disguised) == nil)
        #expect(throws: (any Error).self) {
            _ = try store.write(Data("A mutation".utf8), projectID: a, fileID: fileID, filename: "secret.txt")
        }
        #expect(try store.read(relativePath: saved.path) == Data("B private bytes".utf8))
    }

    @Test("Managed captures and Project removal reject a linked destination")
    func managedParentLink() throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent("FC-managed-path-" + UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: root) }
        let a = UUID(), b = UUID()
        let store = FamiliarManagedFileStore(rootURL: root)
        let original = try store.capture(Data("B output".utf8), filename: "original.txt", projectID: b,
            originKey: "B", runID: nil, toolCallID: nil)
        try FileManager.default.createSymbolicLink(at: root.appendingPathComponent("Projects/" + a.uuidString),
            withDestinationURL: root.appendingPathComponent("Projects/" + b.uuidString))
        #expect(throws: (any Error).self) {
            _ = try store.capture(Data("A output".utf8), filename: "other.txt", projectID: a,
                originKey: "A", runID: nil, toolCallID: nil)
        }
        #expect(throws: (any Error).self) { _ = try store.stageProjectDirectory(projectID: a) }
        #expect(FileManager.default.fileExists(atPath: root.appendingPathComponent(original.storage.relativePath).path))
    }

    @Test("Canonical UI/tool byte reads refuse a managed version reached through another Project's parent link")
    func canonicalReadParentLink() throws {
        let a = UUID(), b = UUID()
        let store = FamiliarManagedFileStore()
        let projects = store.rootURL.appendingPathComponent("Projects")
        defer {
            try? FileManager.default.removeItem(at: projects.appendingPathComponent(a.uuidString))
            try? FileManager.default.removeItem(at: projects.appendingPathComponent(b.uuidString))
        }
        let bytes = Data("B scoped secret".utf8)
        let captured = try store.capture(bytes, filename: "private.txt", projectID: b,
            originKey: "B", runID: nil, toolCallID: nil)
        try FileManager.default.createSymbolicLink(at: projects.appendingPathComponent(a.uuidString),
            withDestinationURL: projects.appendingPathComponent(b.uuidString))
        let snapshot = FamiliarFileSnapshot(reference: .init(fileID: UUID(), versionID: captured.versionID, projectID: a),
            name: "Disguised", origin: .shell, version: 1, filename: captured.filename,
            mimeType: captured.mimeType, byteSize: captured.byteSize, contentHash: captured.contentHash,
            storage: .init(kind: .managed, relativePath: captured.storage.relativePath.replacingOccurrences(of: b.uuidString, with: a.uuidString)),
            isProjectContext: false, updatedAt: Date())
        #expect(FamiliarFileByteReader.url(for: snapshot) == nil)
        #expect(throws: (any Error).self) { _ = try FamiliarFileByteReader.read(snapshot, projectID: a) }
        #expect(try Data(contentsOf: store.rootURL.appendingPathComponent(captured.storage.relativePath)) == bytes)
    }
}
